### ISSUE TITLE
Not working on Atom 1.33.1

### ISSUE THREAD

**Issue by hefler** [voidgraphics/camelify#2]
Nothing happens when trying to "camelify" a string.

**Comment by voidgraphics** [comment]
Just tried it and it works for me. Maybe you have a conflicting keyboard shortcut?
Just a reminder, the default shortcut is control+option+c on mac.

**Comment by hefler** [comment]
Yes, there's some conflicting keyboard shortcut, but even if I go through the `Packages > camelify > Toggle` it doesn't work. 🤔

**Comment by voidgraphics** [comment]
Ah, you're right.

I recommend using the command palette instead if you cannot use a keyboard shortcut. That way works. 

I'll gladly fix it when I find the time.

**Comment by voidgraphics** [comment]
There, you should see an update available. It fixes the menu option and also the one in the context menu (right click) which was broken also.
